### ISSUE TITLE
Some license problem

### ISSUE THREAD

**Issue by sysnote8main** [ripley2459/rtech#45]
# RTech's textures are copyright infringement.

## You would be better off drawing the original texture instead of using from these mods.
- GregTechCEu
- Mekanism

## Why
I want players to know that these textures are the result of other people's efforts.
Also, license violations are not a good thing.

## And Please write credit of [CleanroomMC/TemplateDevEnv](https://github.com/CleanroomMC/TemplateDevEnv).

**Comment by sysnote8main** [comment]
# Mod List
- GregTechCEu
- Mekanism
- TerraFirmaCraft
- FTB Industrial Contraptions

**Comment by MrKono** [comment]
**Textures from _GTCEu_**

https://github.com/ripley2459/rtech/assets/90126004/5fe4025f-e3f8-4878-a650-e1e2d6e3d649


https://github.com/ripley2459/rtech/assets/90126004/b67b9cd3-1869-4b9d-8230-22be5743d3db


https://github.com/ripley2459/rtech/assets/90126004/fa5919ef-7bf0-4458-8d12-09d014421e83


**Textures from _Biomes O' Plenty_**

https://github.com/ripley2459/rtech/assets/90126004/0cbc9f5b-f7eb-4dc5-a452-ee6c4705a681

**Comment by ripley2459** [comment]
I'm going to hide this project while i take steps on this.

**Comment by ripley2459** [comment]
Here are the solutions provided:
- History rewritten to remove any traces of non original textures
- Propers credits

**Comment by bruberu** [comment]
I would probably recommend making new original textures (and putting them on your marketing material). Even if all of the licenses technically allow you to credit them, a lot of people are going to be able to recognize that the textures came from different mods. To them, the mod would seem like a low-effort cash-grab, and they would probably avoid playing it. 

Of course, it does take a lot of work to redo an _entire_ mod's worth of textures, but just keep that in mind.
