### ISSUE TITLE
Hey buddy.

### ISSUE THREAD

**Issue by TheDogOfChaos** [ripley2459/rtech#46]
If you're truly passionate about this project, then please take the time to draw your own textures. Using other people's textures without permission can land you in serious legal trouble & tarnish your reputation within the modding community, so I'd advise changing your ways now while you have the chance.

Please try to replace the textures that you copied from:

- Gregtech CEu (99% of your textures are GTCEu textures)
- Biomes O' Plenty

**Comment by ripley2459** [comment]
Deleting this issue because dup with #45
